# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.1
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/proj/xbuilds/2018.1_0306_1/installs/lin64/Vivado/2018.1/bin/vivado  -notrace -mode batch -source run_ippack.tcl
